### PR TITLE
Only register conflicts if conflicted is attached

### LINKED ISSUE #68: Is it expected that just calling `conflict_prefer()` one time turns on conflict resolution everywhere?
We got a report from a tidymodels user that our narrowly scoped internal calls to `conflict_prefer()` activate the conflicted machinery for everything https://github.com/tidymodels/tidymodels/issues/89

This does seem a little odd. In the below example I'm telling conflicted I _just_ want it to care about `dplyr::select()`, but after `conflict_prefer()` runs it starts to care about everything - in this case that means it starts to care about the fact that mosaic overrides `mean()`.

The original example in the tidymodels issue mentions that one issue with this is that you can't run the code suggestions because conflicted isn't actually attached yet. So if this behavior is expected then one way to improve this might be to namespace prefix the advice with `conflicted::`

``` r
library(mosaic) # masks mean and loads Matrix which also masks mean
#> Registered S3 method overwritten by 'mosaic':
#>   method                           from   
#>   fortify.SpatialPolygonsDataFrame ggplot2
#> 
#> The 'mosaic' package masks several functions from core packages in order to add 
#> additional features.  The original behavior of these functions should not be affected by this.
#> 
#> Attaching package: 'mosaic'
#> The following objects are masked from 'package:dplyr':
#> 
#>     count, do, tally
#> The following object is masked from 'package:Matrix':
#> 
#>     mean
#> The following object is masked from 'package:ggplot2':
#> 
#>     stat
#> The following objects are masked from 'package:stats':
#> 
#>     binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
#>     quantile, sd, t.test, var
#> The following objects are masked from 'package:base':
#> 
#>     max, mean, min, prod, range, sample, sum
library(dplyr)

mean(c(1, 2, 3))
#> [1] 2

conflicted::conflict_prefer("select", winner = "dplyr")
#> [conflicted] Will prefer dplyr::select over any other package

mean(c(1, 2, 3))
#> Error:
#> ! [conflicted] `mean` found in 3 packages.
#> Either pick the one you want with `::` 
#> * mosaic::mean
#> * Matrix::mean
#> * base::mean
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("mean", "mosaic")
#> * conflict_prefer("mean", "Matrix")
#> * conflict_prefer("mean", "base")
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #68

No idea how to test this

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Is this right? Seems like no? You don't expect people to library the conflicted package right?

CRAN:

``` r
library(dplyr, warn.conflicts = FALSE)

conflicted::conflict_prefer("select", winner = "dplyr")
#> [conflicted] Will prefer dplyr::select over any other package

library(MASS)

select
#> function (.data, ...) 
#> {
#>     UseMethod("select")
#> }
#> <bytecode: 0x7fd7d7c87728>
#> <environment: namespace:dplyr>

library(conflicted)

select
#> function (.data, ...) 
#> {
#>     UseMethod("select")
#> }
#> <bytecode: 0x7fd7d7c87728>
#> <environment: namespace:dplyr>
```

This PR:

``` r
library(dplyr, warn.conflicts = FALSE)

conflicted::conflict_prefer("select", winner = "dplyr")
#> [conflicted] Will prefer dplyr::select over any other package

library(MASS)
#> 
#> Attaching package: 'MASS'
#> 
#> The following object is masked from 'package:dplyr':
#> 
#>     select

select
#> function (obj) 
#> UseMethod("select")
#> <bytecode: 0x7fde24ea0038>
#> <environment: namespace:MASS>

library(conflicted)

select
#> function (.data, ...) 
#> {
#>     UseMethod("select")
#> }
#> <bytecode: 0x7fde52ae6b28>
#> <environment: namespace:dplyr>
```

**Comment by DavisVaughan** [comment]
I think this is tough because we have been telling people that all they need to do is call `tidymodels_prefer()`, but now they'd have to `library(conflicted)` too to actually register the conflicts.

I guess that could be considered intentional, and maybe `tidymodels_prefer()` should notify the user if conflicted isn't attached that nothing will happen until it is

``` r
library(tidymodels)
tidymodels_prefer(quiet = FALSE)
#> [conflicted] Will prefer dplyr::filter over any other package
#> [conflicted] Will prefer dplyr::select over any other package
#> [conflicted] Will prefer dplyr::slice over any other package
#> [conflicted] Will prefer dplyr::rename over any other package
#> [conflicted] Will prefer dials::neighbors over any other package
#> [conflicted] Will prefer parsnip::fit over any other package
#> [conflicted] Will prefer parsnip::bart over any other package
#> [conflicted] Will prefer parsnip::pls over any other package
#> [conflicted] Will prefer purrr::map over any other package
#> [conflicted] Will prefer recipes::step over any other package
#> [conflicted] Will prefer themis::step_downsample over any other package
#> [conflicted] Will prefer themis::step_upsample over any other package
#> [conflicted] Will prefer tune::tune over any other package
#> [conflicted] Will prefer yardstick::precision over any other package
#> [conflicted] Will prefer yardstick::recall over any other package
#> [conflicted] Will prefer yardstick::spec over any other package

library(dplyr, warn.conflicts = FALSE)
library(MASS)
#> 
#> Attaching package: 'MASS'
#> 
#> The following object is masked from 'package:dplyr':
#> 
#>     select

select(mtcars)
#> Error in UseMethod("select"): no applicable method for 'select' applied to an object of class "data.frame"
```

<sup>Created on 2022-10-07 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
If we go this route it is probably worth tweaking the README to say "attach" instead of "load"
https://github.com/r-lib/conflicted/blob/1fd25ebee5edfe2887664c730bedb99ea8785332/README.Rmd#L36

**Comment by DavisVaughan** [comment]
> maybe tidymodels_prefer() should notify the user if conflicted isn't attached that nothing will happen until it is

Or maybe this is conflicted's job to show a once per session note about this

**Comment by hadley** [comment]
Yeah, I think this is correct — you have to attach conflicted in order to activate it. 

Are you sure `tidymodels_prefer()` shouldn't just call `library(conflicted)`? But the original issue suggests that you don't want `tidymodels_prefer()` to activate conflicted? 

All `conflicted_prefer()` does is set up some preferences for specific conflicts do arise; it doesn't affect behaviour for any thing else.

**Comment by DavisVaughan** [comment]
I think there was some misconception that you could:
- Use `conflict_prefer()` to specify individual preferences
- Ignore all other conflicts that might arise, like `mean()` conflicts

In my head those are almost two separate features of conflicted. 
- Feature 1 of conflicted is to watch for any conflicts and error if any are seen
- Feature 2 of conflicted is to give you a way to set a preference for where a function should always from, regardless of `library()` order

But you can't use one without the other, and I think that is the main issue. Because yea the original tidymodels issue is that we wanted to activate the tidymodels preferences, but ONLY the tidymodels preferences and ignore everything else that conflicted might watch for (like the `mean()` conflicts).

If it just "doesn't work that way" then we have to decide whether or not `tidymodels_prefer()` should attach conflicted.

**Comment by hadley** [comment]
Your analysis is along the lines of what I was thinking, so I'll close this issue.

But it's good to know that tidymodels has accidentally been widely recommending the use of conflicted, and it appears to have caused few problems.

**Pull request closed without merging**
